#!/bin/bash
set -e

# Parse command line arguments
USAGE="Usage: $0 <yang_file> [<tosca_file>]"

if [[ "$#" == "0" || "$#" -gt "2" ]]; then
   echo "${USAGE}"
   exit 1
fi
YANG_FILE="$1"
TOSCA_FILE="$2"

# Find the TOSCA plugin directory
HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
PLUGINDIR=${HERE}/plugins

# Run the conversion
if [[ "${TOSCA_FILE}" == "" ]]; then
    pyang -f tosca --plugindir "${PLUGINDIR}" "${YANG_FILE}" 
else
    pyang -f tosca --plugindir "${PLUGINDIR}" "${YANG_FILE}" -o "${TOSCA_FILE}"
fi    

