#!/bin/bash
set -e

# Usage message
USAGE="Usage: $0 [ --config|-c <config_file> ] <yang_file> [<tosca_file>]"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
	-c|--config)
	    if [ -z ${CONFIGFILE} ] && [ ! -z "$2" ]; then
		CONFIGFILE="$2"
	    else
		echo $USAGE
		exit 1
	    fi
	    shift # past argument
	    shift # past value
	    ;;
	-*|--*)
	    echo $USAGE
	    exit 1
	    ;;
	*)
	    if [ -z ${YANGFILE} ]; then
		YANGFILE="$1"
	    elif [ -z ${TOSCAFILE} ]; then
		TOSCAFILE="$1"
	    else # Unknown positional argument
		echo $USAGE
		exit 1
	    fi
	    shift # past argument
	    ;;
    esac
done

# Make sure yang file was specified
if [ -z ${YANGFILE} ]; then
    echo $USAGE
    exit 1
fi

# Find the TOSCA plugin directory
PLUGINDIR=$(get_tosca_plugin_dir)

# Create arguments for the pyang command
ARGS="-f tosca --plugindir ${PLUGINDIR}"
if [ ! -z ${TOSCAFILE} ]; then
    ARGS+=" -o ${TOSCAFILE}"
fi
if [ ! -z ${CONFIGFILE} ]; then
    ARGS+=" --tosca-config-file ${CONFIGFILE}"
fi

# Run the conversion
pyang ${ARGS} "${YANGFILE}" 
