#!/bin/bash
set -e

# Parse command line arguments
USAGE="Usage: $0 <yang_file> [<tosca_file>]"

if [[ "$#" == "0" || "$#" -gt "2" ]]; then
   echo "${USAGE}"
   exit 1
fi
YANG_FILE="$1"
TOSCA_FILE="$2"

# Find the TOSCA plugin directory
PLUGINDIR=$(get_tosca_plugin_dir)

# Hardcode the config file for now
CONFIGFILE=${HERE}/config.yaml

# Run the conversion
if [[ "${TOSCA_FILE}" == "" ]]; then
    pyang -f tosca --plugindir "${PLUGINDIR}" --tosca-config-file "${CONFIGFILE}" "${YANG_FILE}" 
else
    pyang -f tosca --plugindir "${PLUGINDIR}" --tosca-config-file "${CONFIGFILE}" "${YANG_FILE}" -o "${TOSCA_FILE}"
fi    

